version: '3.8'

services:
  db:
    container_name: korolev_postgres
    image: postgres:14-alpine
    volumes:
      - korolev_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - "5432"
  scripts:
    container_name: korolev_scripts_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  korolev_postgres_data: