version: "3.8"

services:    
  scripts:
    container_name: korolev_scripts_dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_MODE=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=postgres    
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
  db:
    container_name: korolev_postgres
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=postgres
    expose:
      - "5432"

volumes:
  postgres_data: